<?php

require_once '../appphp/sqldb.php';

date_default_timezone_set("Asia/Taipei");
$localTime = str_replace(',','',(string) date(DATE_RFC850));

$mef01 = [

    [
      'Content'=>'mef01_0',
      'Exp'=>'發行管理資料',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef01_1',
      'Exp'=>'發卡單位編號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_2',
      'Exp'=>'發卡設備編號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_3',
      'Exp'=>'發行批號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_4',
      'Exp'=>'發出日期',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'true',
      'TranscodeRule'=>['Decimal','UnixTime']
    ],
    [
      'Content'=>'mef01_5',
      'Exp'=>'有效日期',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'true',
      'TranscodeRule'=>['Decimal','UnixTime']
    ],
    [
      'Content'=>'mef01_6',
      'Exp'=>'卡片格式版本',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_7',
      'Exp'=>'卡片狀態',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_8',
      'Exp'=>'檢查碼',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_09',
      'Exp'=>'票值管理資料',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef01_10',
      'Exp'=>'自動加值設定',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_11',
      'Exp'=>'自動加值票值數額',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_12',
      'Exp'=>'儲存最大票值數額',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_13',
      'Exp'=>'每筆可加減最大票值數額',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_14',
      'Exp'=>'指定加值設定',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_15',
      'Exp'=>'指定加值票值數額',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_16',
      'Exp'=>'自動加值日期',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'true',
      'TranscodeRule'=>['Decimal','UnixTime']
    ],
    [
      'Content'=>'mef01_17',
      'Exp'=>'連續離線自動加值次數',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_18',
      'Exp'=>'連續自動加值次數',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_19',
      'Exp'=>'連續指定加值次數',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_20',
      'Exp'=>'檢查碼',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef01_21',
      'Exp'=>'卡片防偽驗證資料',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [

      'Content'=>'mef01_22',
      'Exp'=>'防偽驗證資料',
      'length'=>32,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ]
];

$mef03 = [
    [
      'Content'=>'mef03_0',
      'Exp'=>'卡片交易狀態資料',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef03_1',
      'Exp'=>'卡片交易序號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_2',
      'Exp'=>'交易紀錄指標',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_3',
      'Exp'=>'優惠積點數',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_4',
      'Exp'=>'優惠積點交易序號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_5',
      'Exp'=>'鎖卡旗標',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_6',
      'Exp'=>'進出閘門口編號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_7',
      'Exp'=>'進出閘門口時間',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'true',
      'TranscodeRule'=>['LSB','Decimal','UnixTime']
    ],
    [
      'Content'=>'mef03_8',
      'Exp'=>'轉乘Flag(交易類別)',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_9',
      'Exp'=>'轉乘Flag(交易群組)',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_10',
      'Exp'=>'最近兩筆閘門交易紀錄(1)',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef03_11',
      'Exp'=>'交易序號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_12',
      'Exp'=>'交易時間',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'true',
      'TranscodeRule'=>['LSB','Decimal','UnixTime']
    ],
    [
      'Content'=>'mef03_13',
      'Exp'=>'交易類別',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_14',
      'Exp'=>'交易票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_15',
      'Exp'=>'交易後票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_16',
      'Exp'=>'交易系統編號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_17',
      'Exp'=>'交易地點/運輸業者',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_18',
      'Exp'=>'交易機器',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_19',
      'Exp'=>'最近兩筆閘門交易紀錄(2)',
      'length'=>0,
      'dataCoding'=>null,
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef03_20',
      'Exp'=>'交易序號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_21',
      'Exp'=>'交易時間',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'true',
      'TranscodeRule'=>['LSB','Decimal','UnixTime']
    ],
    [
      'Content'=>'mef03_22',
      'Exp'=>'交易類別',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_23',
      'Exp'=>'交易票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_24',
      'Exp'=>'交易後票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef03_25',
      'Exp'=>'交易系統編號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_26',
      'Exp'=>'交易地點/運輸業者',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef03_27',
      'Exp'=>'交易機器',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ]
];

$mef08 = [
  [
    'Content'=>'mef08_0',
    'Exp'=>'里程客運進出站交易管理資料',
    'length'=>0,
    'dataCoding'=>null,
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>null
  ],
  [
    'Content'=>'mef08_1',
    'Exp'=>'客運公司編號',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_2',
    'Exp'=>'最後一次上/下車碼',
    'length'=>'2-4',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-0-1-LSB']
  ],
  [
    'Content'=>'mef08_3',
    'Exp'=>'里程特種票類別代碼',
    'length'=>'2-4',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-1-4-LSB']
  ],
  [
    'Content'=>'mef08_4',
    'Exp'=>'保留',
    'length'=>'2-4',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-4-8-LSB']
  ],
  [
    'Content'=>'mef08_5',
    'Exp'=>'里程特種票原始可用次數/額度',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_6',
    'Exp'=>'里程特種票剩餘可用次數/額度',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_7',
    'Exp'=>'里程特種票有效日期',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_8',
    'Exp'=>'里程特種票有效天數',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_9',
    'Exp'=>'里程特種票有效起站',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_10',
    'Exp'=>'里程特種票有效迄站',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_11',
    'Exp'=>'當日累積里程交易日期',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_12',
    'Exp'=>'當日累積里程搭乘金額',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_13',
    'Exp'=>'最後一次搭乘路線編號',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_14',
    'Exp'=>'里程計費上車交易紀錄',
    'length'=>0,
    'dataCoding'=>null,
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>null
  ],
  [
    'Content'=>'mef08_15',
    'Exp'=>'交易時間',
    'length'=>8,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'true',
    'TranscodeRule'=>['LSB','Decimal','UnixTime']
  ],
  [
    'Content'=>'mef08_16',
    'Exp'=>'交易票值',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_17',
    'Exp'=>'交易後票值',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_18',
    'Exp'=>'交易類別',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_19',
    'Exp'=>'上車站別ID',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_20',
    'Exp'=>'交易序號',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_21',
    'Exp'=>'交易地點/運輸業者(DEV_ID)',
    'length'=>8,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_22',
    'Exp'=>'行駛方向(往程=>1返程=>2循環=>3)',
    'length'=>'62-64',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-0-4-LSB']
  ],
  [
    'Content'=>'mef08_23',
    'Exp'=>'保留',
    'length'=>'62-64',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-4-8-LSB']
  ],
  [
    'Content'=>'mef08_24',
    'Exp'=>'里程計費下車交易紀錄',
    'length'=>0,
    'dataCoding'=>null,
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>null
  ],
  [
    'Content'=>'mef08_25',
    'Exp'=>'交易時間',
    'length'=>8,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'true',
    'TranscodeRule'=>['LSB','Decimal','UnixTime']
  ],
  [
    'Content'=>'mef08_26',
    'Exp'=>'交易票值',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_27',
    'Exp'=>'交易後票值',
    'length'=>4,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_28',
    'Exp'=>'交易類別',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_29',
    'Exp'=>'上車站別ID',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_30',
    'Exp'=>'交易序號',
    'length'=>2,
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Decimal']
  ],
  [
    'Content'=>'mef08_31',
    'Exp'=>'交易地點/運輸業者(DEV_ID)',
    'length'=>8,
    'dataCoding'=>'BIN',
    'LSB'=>'true',
    'UnixTime'=>'false',
    'TranscodeRule'=>['LSB','Decimal']
  ],
  [
    'Content'=>'mef08_32',
    'Exp'=>'行駛方向(往程=>1返程=>2循環=>3)',
    'length'=>'94-96',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-0-4-LSB']
  ],
  [
    'Content'=>'mef08_33',
    'Exp'=>'保留',
    'length'=>'94-96',
    'dataCoding'=>'BIN',
    'LSB'=>'false',
    'UnixTime'=>'false',
    'TranscodeRule'=>['Binary-4-8-LSB']
  ]
];

$mef0b = [
    [
      'Content'=>'mef0b_0',
      'Exp'=>'段次公車/客運特種票資料區',
      'length'=>0,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef0b_1',
      'Exp'=>'段次特種票識別單位',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_2',
      'Exp'=>'段次特種票類別代碼',
      'length'=>'2-4',
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Binary-0-3-LSB']
    ],
    [
      'Content'=>'mef0b_3',
      'Exp'=>'保留',
      'length'=>'2-4',
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Binary-3-8-LSB']
    ],
    [
      'Content'=>'mef0b_4',
      'Exp'=>'段次特種票原始可用次數/額度',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_5',
      'Exp'=>'段次特種票剩餘可用次數/額度',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_6',
      'Exp'=>'段次特種票有效日期',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_7',
      'Exp'=>'段次特種票有效天數',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_8',
      'Exp'=>'段次特種票有效起站',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_9',
      'Exp'=>'段次特種票有效迄站',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_10',
      'Exp'=>'段次特種票保留',
      'length'=>10,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_11',
      'Exp'=>'段次公車/客運交易資料',
      'length'=>0,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef0b_12',
      'Exp'=>'路線編號',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef0b_13',
      'Exp'=>'交易時間',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'true',
      'TranscodeRule'=>['LSB','Decimal','UnixTime']
    ],
    [
      'Content'=>'mef0b_14',
      'Exp'=>'交易票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef0b_15',
      'Exp'=>'交易後票值',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'true',
      'UnixTime'=>'false',
      'TranscodeRule'=>['LSB','Decimal']
    ],
    [
      'Content'=>'mef0b_16',
      'Exp'=>'交易類別',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_17',
      'Exp'=>'交易地點/運輸業者(DEV_ID)',
      'length'=>8,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_18',
      'Exp'=>'段號',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_19',
      'Exp'=>'保留',
      'length'=>0,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>null
    ],
    [
      'Content'=>'mef0b_20',
      'Exp'=>'當日累積段次交易日期',
      'length'=>4,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_21',
      'Exp'=>'當日累積段次搭乘次數',
      'length'=>2,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ],
    [
      'Content'=>'mef0b_22',
      'Exp'=>'保留',
      'length'=>26,
      'dataCoding'=>'BIN',
      'LSB'=>'false',
      'UnixTime'=>'false',
      'TranscodeRule'=>['Decimal']
    ]

];

$line_number = 1;
foreach ($mef0b as $key => $row) {
  foreach ($row as $key => $value) {

    if(gettype($value) !== 'array'){

      echo $key.':'.$value.'<br>';

      if($key === 'Content'){
        $Subject = $value;
        $content = $value;
      }
      if($key === 'Exp') $exp = $value;
      if($key === 'length') $length = $value;
      if($key === 'dataCoding') $data_coding = $value;
      if($key === 'LSB') $lsb = $value;
      if($key === 'UnixTime') $unixtime = $value;
      if($key === 'TranscodeRule') $Rule = null;

    }elseif (gettype($value) === 'array') {

      $Rule = '';
      foreach ($value as $key => $rule) {
        if($key === count($value)-1){
          $Rule .= $rule;
        }else {
          $Rule .= $rule.',';
        }
      }

      echo 'Rule : '.$Rule.'<br>';

    }

  }

  $rule_set_id = 5;
  $rule_name = 'mef0b';
  $rule_var = 'RuleSet_5';



  $query = "INSERT INTO
  TransCodeRule(RuleSetID,RuleName,RuleVar,LineNumber,Subject,Content,Exp,Length,DataCoding,LSB,UnixTime,TranscodeRule,CreateTime,Marked)
  VALUES (".$rule_set_id.",'".$rule_name."','".$rule_var."',".$line_number.",
  '".$Subject."','".$content."','".$exp."',".$length.",'".$data_coding."','".$lsb."','".$unixtime."','".$Rule."','".$localTime."',
  'false')";

  echo $query.'<br>';

  $conn->query('SET NAMES UTF8');
  $conn->query($query);


  $line_number ++;
  echo '========Row=========<br>';
}


 ?>
